# Generated by Django 4.1.3 on 2022-11-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_student_bio_alter_student_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studAvailability', models.DateField(max_length=10)),
                ('numOfLessons', models.IntegerField(max_length=2)),
                ('frequencyLessons', models.CharField(choices=[('weekly', 'Every week'), ('fortnightly', 'Every 2 weeks')], max_length=20)),
                ('lessonDuration', models.CharField(choices=[('30', '30 mins'), ('60', '60 mins')], max_length=2)),
                ('moreInfo', models.TextField(max_length=200)),
            ],
        ),
    ]
