# Generated by Django 4.1.3 on 2022-11-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='numOfLessons',
            field=models.IntegerField(max_length=10),
        ),
    ]
