# Generated by Django 4.1.3 on 2022-11-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_request_numoflessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='numOfLessons',
            field=models.CharField(max_length=2),
        ),
    ]
