# Generated by Django 4.1.3 on 2022-11-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_request_numoflessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='studAvailability',
            field=models.CharField(max_length=10),
        ),
    ]
