# Generated by Django 4.1.3 on 2022-11-27 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_request_studavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
