# Generated by Django 4.1.3 on 2022-11-29 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_remove_request_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='moreInfo',
            new_name='Extra_Information',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='frequencyLessons',
            new_name='Frequency_Lessons',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='lessonDuration',
            new_name='Lesson_Duration',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='numOfLessons',
            new_name='Number_Of_Lessons',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='studAvailability',
            new_name='Student_Availability',
        ),
    ]
