# Generated by Django 4.1.3 on 2022-11-30 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_rename_moreinfo_request_extra_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='studentReq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
