# Generated by Django 4.1.3 on 2022-12-01 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_alter_request_studentreq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Extra_Information',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='Number_Of_Lessons',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='request',
            name='Student_Availability',
            field=models.CharField(choices=[('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday')], max_length=30),
        ),
    ]
