# Generated by Django 4.1.3 on 2022-12-03 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_request_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='BookedDay',
            field=models.CharField(choices=[('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday')], default='monday', max_length=30),
        ),
        migrations.AddField(
            model_name='request',
            name='BookedInterval',
            field=models.CharField(choices=[('weekly', 'Every week'), ('fortnightly', 'Every 2 weeks')], default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='request',
            name='StartDate',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2022, 12, 3, 17, 51, 43, 984136), null=None),
        ),
        migrations.AlterField(
            model_name='request',
            name='Booked',
            field=models.BooleanField(default=False),
        ),
    ]
