# Generated by Django 4.1.3 on 2022-12-03 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_request_bookedday_request_bookedinterval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='StartDate',
            field=models.DateTimeField(blank=None, default=django.utils.timezone.now, null=None),
        ),
    ]
