# Generated by Django 4.1.3 on 2022-12-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_request_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='Lesson_Time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
