# Generated by Django 4.1.3 on 2022-12-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_request_lesson_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='Booked',
            field=models.BooleanField(default=False),
        ),
    ]
