# Generated by Django 4.1.3 on 2022-12-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_remove_request_lesson_time_remove_request_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='Teacher',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
