# Generated by Django 4.1.4 on 2022-12-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_request_lesson_time_alter_request_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='Lesson_Time',
        ),
        migrations.RemoveField(
            model_name='request',
            name='Teacher',
        ),
    ]
