# Generated by Django 4.1.4 on 2022-12-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0022_remove_request_lesson_time_remove_request_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='Booked',
            new_name='booked',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='BookedDay',
            new_name='booked_day',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='BookedInterval',
            new_name='booked_interval',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Extra_Information',
            new_name='extra_information',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Frequency_Lessons',
            new_name='frequency_lessons',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Lesson_Duration',
            new_name='lesson_duration',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Number_Of_Lessons',
            new_name='number_of_lessons',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='StartDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='Student_Availability',
            new_name='student_availability',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='studentReq',
            new_name='student_username',
        ),
    ]
