# Generated by Django 4.1.4 on 2022-12-08 06:46

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0023_rename_booked_request_booked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=0, max_length=4)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='student_reference_number',
            field=models.CharField(default=uuid.uuid1, max_length=4),
        ),
    ]
